networks:
  jenkins-network:
    external: true
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /volume1/docker/sre/prometheus/etc:/etc/prometheus
      - /volume1/docker/sre/prometheus/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - jenkins-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 6001:3000
    volumes:
      - /volume1/docker/sre/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - jenkins-network
